version: "3"
services:
    appie:
        image: netfloex/appie:latest
        container_name: appie
        ports:
            - 2000:3000
        volumes:
            - ./data:/data
        environment:
            AH_USERNAME: username
            AH_PASSWORD: password
