name: docker-build

on:
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup NodeJS v12
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Cache Dependencies
              uses: c-hive/gha-yarn-cache@v2

            - name: Install Dependencies
              run: yarn install

            - name: Test Typescript
              run: yarn test
            - name: Test ESLint
              run: yarn lint
            - name: Test Stylelint
              run: yarn stylelint

    docker:
        runs-on: ubuntu-latest
        needs: tests
        steps:
            # Setup
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
              # Needed until buildx 0.6 and BuildKit 0.9 are released
              with:
                  version: v0.6.0-rc1
                  driver-opts: image=moby/buildkit:master

            # Login
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Build & Push
            - name: Build Dockerfile and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: netfloex/appie:latest

                  # Cache
                  cache-from: type=gha
                  cache-to: type=gha
