name: docker-build

on:
    push:
        branches:
            - master

jobs:
    typescript:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup NodeJS v12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Install all dependencies
              run: yarn install
            - name: Test Typescript
              run: yarn test
    docker:
        runs-on: ubuntu-latest
        needs: typescript
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build Dockerfile and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: netfloex/api:latest
            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
