name: docker-build

on:
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Setup yarn and install dependencies
              uses: netfloex/actions/yarn@master

            - name: Test Typescript
              run: yarn typescript
            - name: Test ESLint
              run: yarn lint
            - name: Test Stylelint
              run: yarn stylelint

    docker:
        runs-on: ubuntu-latest
        needs: tests
        steps:
            - name: Build and push to docker hub
              uses: netfloex/actions/docker@master
              with:
                  username: netfloex
                  token: ${{ secrets.DOCKERHUB_TOKEN }}
                  tags: netfloex/appie:latest
